<a href="https://colab.research.google.com/github/ECastro08/Challenge-TelecomX/blob/main/challengeTelecomX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import requests
import numpy as np

## **Extraccion de los datos**

In [2]:
url = 'https://raw.githubusercontent.com/ingridcristh/challenge2-data-science-LATAM/refs/heads/main/TelecomX_Data.json'

In [3]:
response = requests.get(url)
data = response.json()
df_telecom = pd.DataFrame(data)
df_telecom.head()

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."

### **Normalizando los datos**

In [4]:
df_telecom = pd.json_normalize(data)
df_telecom.head()

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

## **Transformacion**

In [5]:
df_telecom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   object
 1   Churn                      7267 non-null   object
 2   customer.gender            7267 non-null   object
 3   customer.SeniorCitizen     7267 non-null   int64
 4   customer.Partner           7267 non-null   object
 5   customer.Dependents        7267 non-null   object
 6   customer.tenure            7267 non-null   int64
 7   phone.PhoneService         7267 non-null   object
 8   phone.MultipleLines        7267 non-null   object
 9   internet.InternetService   7267 non-null   object
 10  internet.OnlineSecurity    7267 non-null   object
 11  internet.OnlineBackup      7267 non-null   object
 12  internet.DeviceProtection  7267 non-null   object
 13  internet.TechSupport       7267 non-null   object
 14  internet.StreamingTV       7267 non-null   object
 15  internet.StreamingMovies   7267 non-null   object
 16  account.Contract           7267 non-null   object
 17  account.PaperlessBilling   7267 non-null   object
 18  account.PaymentMethod      7267 non-null   object
 19  account.Charges.Monthly    7267 non-null   float64
 20  account.Charges.Total      7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

### Incoherencias
Aplicar la funcion unique a las columnas categoricas para detectar posibles anomalias

In [6]:
categorical_cols = df_telecom.select_dtypes(include='object').columns

In [7]:
categorical_cols

Index(['customerID', 'Churn', 'customer.gender', 'customer.Partner',
       'customer.Dependents', 'phone.PhoneService', 'phone.MultipleLines',
       'internet.InternetService', 'internet.OnlineSecurity',
       'internet.OnlineBackup', 'internet.DeviceProtection',
       'internet.TechSupport', 'internet.StreamingTV',
       'internet.StreamingMovies', 'account.Contract',
       'account.PaperlessBilling', 'account.PaymentMethod',
       'account.Charges.Total'],
      dtype='object')

In [8]:
from enum import unique
for col in categorical_cols:
  print(f'valores de {col}: {df_telecom[col].unique()}')

valores de customerID: ['0002-ORFBO' '0003-MKNFE' '0004-TLHLJ' ... '9992-UJOEL' '9993-LHIEB'
 '9995-HOTOH']
valores de Churn: ['No' 'Yes' '']
valores de customer.gender: ['Female' 'Male']
valores de customer.Partner: ['Yes' 'No']
valores de customer.Dependents: ['Yes' 'No']
valores de phone.PhoneService: ['Yes' 'No']
valores de phone.MultipleLines: ['No' 'Yes' 'No phone service']
valores de internet.InternetService: ['DSL' 'Fiber optic' 'No']
valores de internet.OnlineSecurity: ['No' 'Yes' 'No internet service']
valores de internet.OnlineBackup: ['Yes' 'No' 'No internet service']
valores de internet.DeviceProtection: ['No' 'Yes' 'No internet service']
valores de internet.TechSupport: ['Yes' 'No' 'No internet service']
valores de internet.StreamingTV: ['Yes' 'No' 'No internet service']
valores de internet.StreamingMovies: ['No' 'Yes' 'No internet service']
valores de account.Contract: ['One year' 'Month-to-month' 'Two year']
valores de account.PaperlessBilling: ['Yes' 'No']
valores de account.PaymentMethod: ['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']
valores de account.Charges.Total: ['593.3' '542.4' '280.85' ... '742.9' '4627.65' '3707.6']

Revisando las columnas anteriores se detecto un mal formato de la columna .Total y un string vacio en la columna churn.

### **Manejo de inconsistencias**

In [9]:
# conviertiendo a formato numerico
df_telecom['account.Charges.Total'] = pd.to_numeric(df_telecom['account.Charges.Total'],errors='coerce')

In [10]:
# reviso nuevamente la informacion del dataset
df_telecom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   object
 1   Churn                      7267 non-null   object
 2   customer.gender            7267 non-null   object
 3   customer.SeniorCitizen     7267 non-null   int64
 4   customer.Partner           7267 non-null   object
 5   customer.Dependents        7267 non-null   object
 6   customer.tenure            7267 non-null   int64
 7   phone.PhoneService         7267 non-null   object
 8   phone.MultipleLines        7267 non-null   object
 9   internet.InternetService   7267 non-null   object
 10  internet.OnlineSecurity    7267 non-null   object
 11  internet.OnlineBackup      7267 non-null   object
 12  internet.DeviceProtection  7267 non-null   object
 13  internet.TechSupport       7267 non-null   object
 14  internet.StreamingTV       7267 non-null   object
 15  internet.StreamingMovies   7267 non-null   object
 16  account.Contract           7267 non-null   object
 17  account.PaperlessBilling   7267 non-null   object
 18  account.PaymentMethod      7267 non-null   object
 19  account.Charges.Monthly    7267 non-null   float64
 20  account.Charges.Total      7256 non-null   float64
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [11]:
df_telecom.describe()

,customer.SeniorCitizen,customer.tenure,account.Charges.Monthly,account.Charges.Total
count,7267.000000,7267.000000,7267.000000,7256.000000
mean,0.162653,32.346498,64.720098,2280.634213
std,0.369074,24.571773,30.129572,2268.632997
min,0.000000,0.000000,18.250000,18.800000
25%,0.000000,9.000000,35.425000,400.225000
50%,0.000000,29.000000,70.300000,1391.000000
75%,0.000000,55.000000,89.875000,3785.300000
max,1.000000,72.000000,118.750000,8684.800000

#### valores nulos

In [12]:
# buscamos valores nulos
df_telecom.isnull().sum()

customerID                    0
Churn                         0
customer.gender               0
customer.SeniorCitizen        0
customer.Partner              0
customer.Dependents           0
customer.tenure               0
phone.PhoneService            0
phone.MultipleLines           0
internet.InternetService      0
internet.OnlineSecurity       0
internet.OnlineBackup         0
internet.DeviceProtection     0
internet.TechSupport          0
internet.StreamingTV          0
internet.StreamingMovies      0
account.Contract              0
account.PaperlessBilling      0
account.PaymentMethod         0
account.Charges.Monthly       0
account.Charges.Total        11
dtype: int64

In [13]:
# valores nulos en la columna account.Charges.Total
nulls = df_telecom[df_telecom['account.Charges.Total'].isnull()]

In [14]:
nulls['customer.tenure'].value_counts()

customer.tenure
0    11
Name: count, dtype: int64

Lo realacionamos con la columna customer.Tenure porque si el tenure que es la cantidad de meses que lleva el cliente es igual a 0, quiere decir que es un cliente nuevo, por ende aun no hay cargo a pagar.

In [15]:
# llenar los campos nulos con 0
df_telecom.loc[
    (df_telecom['account.Charges.Total'].isna()) & (df_telecom['customer.tenure'] == 0),
    'account.Charges.Total'
] = 0

In [16]:
# buscamos valores nulos nuevamente
df_telecom.isnull().sum()

customerID                   0
Churn                        0
customer.gender              0
customer.SeniorCitizen       0
customer.Partner             0
customer.Dependents          0
customer.tenure              0
phone.PhoneService           0
phone.MultipleLines          0
internet.InternetService     0
internet.OnlineSecurity      0
internet.OnlineBackup        0
internet.DeviceProtection    0
internet.TechSupport         0
internet.StreamingTV         0
internet.StreamingMovies     0
account.Contract             0
account.PaperlessBilling     0
account.PaymentMethod        0
account.Charges.Monthly      0
account.Charges.Total        0
dtype: int64

#### Strings vacios

In [17]:
# vamos a trabajar con esta columna donde vamos a analizar porque se genero ese string vacio y despues eliminar ese string vacio
df_telecom['Churn'].unique()

array(['No', 'Yes', ''], dtype=object)

In [18]:
df_telecom['Churn'] = df_telecom['Churn'].replace('', pd.NA)

In [19]:
nulos = df_telecom['Churn'].isna().sum()
total_registros = len(df_telecom)
porcentaje = (nulos / total_registros) * 100

print(f"Los registros sin Churn representan el {porcentaje:.2f}% del total")

Los registros sin Churn representan el 3.08% del total

De acuerdo a la informacion recolectada se obtienen un total de 224 registros en los cuales existe esta presente el string vacio lo que equivale al 3% del total, buscando informacion para su tratamiento lo mas adecuado es eliminarlos ya que es un porcentaje reducido lo que produce bajo impacto estadistico.

In [20]:
# Eliminacion de los registros
df_telecom = df_telecom.dropna(subset=['Churn'])
df_telecom['Churn'].unique()

array(['No', 'Yes'], dtype=object)

In [21]:
# ELiminar cualquier espacio en las columnas categoricas
categorical_cols = df_telecom.select_dtypes(include='object').columns
df_telecom[categorical_cols] = df_telecom[categorical_cols].apply(lambda x: x.str.strip())

In [22]:
df_telecom.sample(5)

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
5868,8023-QHAIO,No,Female,1,Yes,No,56,Yes,Yes,Fiber optic,...,No,No,Yes,No,No,Month-to-month,Yes,Bank transfer (automatic),76.85,4275.75
521,0739-UUAJR,No,Female,0,Yes,Yes,72,No,No phone service,DSL,...,No,Yes,No,Yes,Yes,Two year,Yes,Credit card (automatic),53.80,3952.45
6846,9445-SZLCH,Yes,Female,0,Yes,Yes,36,Yes,Yes,Fiber optic,...,Yes,Yes,No,Yes,No,Month-to-month,Yes,Bank transfer (automatic),97.35,3457.90
2834,3932-IJWDZ,No,Male,0,No,No,45,Yes,Yes,Fiber optic,...,No,Yes,Yes,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.65,4747.85
4919,6725-TPKJO,No,Male,0,No,No,44,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.05,845.25

In [23]:
df_telecom.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7043 non-null   object
 1   Churn                      7043 non-null   object
 2   customer.gender            7043 non-null   object
 3   customer.SeniorCitizen     7043 non-null   int64
 4   customer.Partner           7043 non-null   object
 5   customer.Dependents        7043 non-null   object
 6   customer.tenure            7043 non-null   int64
 7   phone.PhoneService         7043 non-null   object
 8   phone.MultipleLines        7043 non-null   object
 9   internet.InternetService   7043 non-null   object
 10  internet.OnlineSecurity    7043 non-null   object
 11  internet.OnlineBackup      7043 non-null   object
 12  internet.DeviceProtection  7043 non-null   object
 13  internet.TechSupport       7043 non-null   object
 14  internet.StreamingTV       7043 non-null   object
 15  internet.StreamingMovies   7043 non-null   object
 16  account.Contract           7043 non-null   object
 17  account.PaperlessBilling   7043 non-null   object
 18  account.PaymentMethod      7043 non-null   object
 19  account.Charges.Monthly    7043 non-null   float64
 20  account.Charges.Total      7043 non-null   float64
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

Se realizo el tratamiento de inconsistencias y se dejo el dataset limpio para las etapas posteriores

### Columna Cuentas Diarias

In [24]:
df_telecom['cuentas_diarias'] = df_telecom['account.Charges.Monthly']/30

In [25]:
df_telecom.head()

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total,cuentas_diarias
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.30,2.186667
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.40,1.996667
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85,2.463333
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85,3.266667
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.40,2.796667

### Estandarizacion y transformacion

#### variables Binarias

In [26]:
# columnas con valores Yes-No
df_telecom['customer.Partner'] = df_telecom['customer.Partner'].map({'Yes': 1, 'No': 0})
df_telecom['customer.Dependents'] = df_telecom['customer.Dependents'].map({'Yes': 1, 'No': 0})
df_telecom['phone.PhoneService'] = df_telecom['phone.PhoneService'].map({'Yes': 1, 'No': 0})
df_telecom['phone.MultipleLines'] = df_telecom['phone.MultipleLines'].map({'Yes': 1, 'No': 0, 'No phone service': 0})
df_telecom['internet.OnlineSecurity'] = df_telecom['internet.OnlineSecurity'].map({'Yes': 1, 'No': 0, 'No internet service': 0})
df_telecom['internet.OnlineBackup'] = df_telecom['internet.OnlineBackup'].map({'Yes': 1, 'No': 0, 'No internet service': 0})
df_telecom['internet.DeviceProtection'] = df_telecom['internet.DeviceProtection'].map({'Yes': 1, 'No': 0, 'No internet service': 0})
df_telecom['internet.TechSupport'] = df_telecom['internet.TechSupport'].map({'Yes': 1, 'No': 0, 'No internet service': 0})
df_telecom['internet.StreamingTV'] = df_telecom['internet.StreamingTV'].map({'Yes': 1, 'No': 0, 'No internet service': 0})
df_telecom['internet.StreamingMovies'] = df_telecom['internet.StreamingMovies'].map({'Yes': 1, 'No': 0, 'No internet service': 0})
df_telecom['account.PaperlessBilling'] = df_telecom['account.PaperlessBilling'].map({'Yes': 1, 'No': 0})

#### Renombrar columnas

In [27]:
df_telecom = df_telecom.rename(columns={
    'customerID': 'customer_id',
    'Churn': 'churn',
    'customer.gender': 'gender',
    'customer.SeniorCitizen': 'senior_citizen',
    'customer.Partner': 'partner',
    'customer.Dependents': 'dependents',
    'customer.tenure': 'tenure',
    'phone.PhoneService': 'phone_service',
    'phone.MultipleLines': 'multiple_lines',
    'internet.InternetService': 'internet_service',
    'internet.OnlineSecurity': 'online_security',
    'internet.OnlineBackup': 'online_backup',
    'internet.DeviceProtection': 'device_protection',
    'internet.TechSupport': 'tech_support',
    'internet.StreamingTV': 'streaming_tv',
    'internet.StreamingMovies': 'streaming_movies',
    'account.Contract': 'contract',
    'account.PaperlessBilling': 'paperless_billing',
    'account.PaymentMethod': 'payment_method',
    'account.Charges.Monthly': 'monthly_charges',
    'account.Charges.Total': 'total_charges'
})

In [28]:
df_telecom.head()

,customer_id,churn,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,...,device_protection,tech_support,streaming_tv,streaming_movies,contract,paperless_billing,payment_method,monthly_charges,total_charges,cuentas_diarias
0,0002-ORFBO,No,Female,0,1,1,9,1,0,DSL,...,0,1,1,0,One year,1,Mailed check,65.6,593.30,2.186667
1,0003-MKNFE,No,Male,0,0,0,9,1,1,DSL,...,0,0,0,1,Month-to-month,0,Mailed check,59.9,542.40,1.996667
2,0004-TLHLJ,Yes,Male,0,0,0,4,1,0,Fiber optic,...,1,0,0,0,Month-to-month,1,Electronic check,73.9,280.85,2.463333
3,0011-IGKFF,Yes,Male,1,1,0,13,1,0,Fiber optic,...,1,0,1,1,Month-to-month,1,Electronic check,98.0,1237.85,3.266667
4,0013-EXCHZ,Yes,Female,1,1,0,3,1,0,Fiber optic,...,0,1,1,0,Month-to-month,1,Mailed check,83.9,267.40,2.796667

In [29]:
df_telecom.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 0 to 7266
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        7043 non-null   object
 1   churn              7043 non-null   object
 2   gender             7043 non-null   object
 3   senior_citizen     7043 non-null   int64
 4   partner            7043 non-null   int64
 5   dependents         7043 non-null   int64
 6   tenure             7043 non-null   int64
 7   phone_service      7043 non-null   int64
 8   multiple_lines     7043 non-null   int64
 9   internet_service   7043 non-null   object
 10  online_security    7043 non-null   int64
 11  online_backup      7043 non-null   int64
 12  device_protection  7043 non-null   int64
 13  tech_support       7043 non-null   int64
 14  streaming_tv       7043 non-null   int64
 15  streaming_movies   7043 non-null   int64
 16  contract           7043 non-null   object
 17  paperless_billing  7043 non-null   int64
 18  payment_method     7043 non-null   object
 19  monthly_charges    7043 non-null   float64
 20  total_charges      7043 non-null   float64
 21  cuentas_diarias    7043 non-null   float64
dtypes: float64(3), int64(13), object(6)
memory usage: 1.2+ MB

In [30]:
df_telecom.isna().sum()

customer_id          0
churn                0
gender               0
senior_citizen       0
partner              0
dependents           0
tenure               0
phone_service        0
multiple_lines       0
internet_service     0
online_security      0
online_backup        0
device_protection    0
tech_support         0
streaming_tv         0
streaming_movies     0
contract             0
paperless_billing    0
payment_method       0
monthly_charges      0
total_charges        0
cuentas_diarias      0
dtype: int64

**Se realizó la estandarización de variables binarias y el renombrado de columnas para mejorar la consistencia y claridad del dataset. Estas transformaciones facilitan el análisis exploratorio y preparan los datos para futuras etapas de modelado, sin comprometer la interpretabilidad de las variables.**

## **Carga y Analisis**

### **Analisis Descriptivo**

In [37]:
# Variables numericas
df_telecom.describe()

,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,online_security,online_backup,device_protection,tech_support,streaming_tv,streaming_movies,paperless_billing,monthly_charges,total_charges,cuentas_diarias
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,0.162147,0.483033,0.299588,32.371149,0.903166,0.421837,0.286668,0.344881,0.343888,0.290217,0.384353,0.387903,0.592219,64.761692,2279.734304,2.158723
std,0.368612,0.499748,0.458110,24.559481,0.295752,0.493888,0.452237,0.475363,0.475038,0.453895,0.486477,0.487307,0.491457,30.090047,2266.794470,1.003002
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.250000,0.000000,0.608333
25%,0.000000,0.000000,0.000000,9.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,35.500000,398.550000,1.183333
50%,0.000000,0.000000,0.000000,29.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,70.350000,1394.550000,2.345000
75%,0.000000,1.000000,1.000000,55.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,89.850000,3786.600000,2.995000
max,1.000000,1.000000,1.000000,72.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,118.750000,8684.800000,3.958333

In [42]:
df_telecom[['tenure', 'monthly_charges', 'total_charges']].describe()

            tenure  monthly_charges  total_charges
count  7043.000000      7043.000000    7043.000000
mean     32.371149        64.761692    2279.734304
std      24.559481        30.090047    2266.794470
min       0.000000        18.250000       0.000000
25%       9.000000        35.500000     398.550000
50%      29.000000        70.350000    1394.550000
75%      55.000000        89.850000    3786.600000
max      72.000000       118.750000    8684.800000

In [40]:
# variables categoricas
categorical = df_telecom.select_dtypes(include='object')
categorical.describe()

,customer_id,churn,gender,internet_service,contract,payment_method
count,7043,7043,7043,7043,7043,7043
unique,7043,2,2,3,3,4
top,9995-HOTOH,No,Male,Fiber optic,Month-to-month,Electronic check
freq,1,5174,3555,3096,3875,2365

Analizadas cada una de las columnas y sus tipos de datos,se concluye que las columnas mas relevenates para el analisis de la evasion de clientes son:

* Churn (Objetivo)
* customer.tenure
* account.Contract

* account.Charges.Monthly

* account.PaymentMethod

* internet.TechSupport

* internet.InternetService

* internet.OnlineSecurity

* account.Charges.Total

* customer.SeniorCitizen